metadata:
  source: wss://babylon-sub-1.joystream.app/staging/rpc
  blockHash: '0x206a6cca31333cb19ee120cde7455e13eea368ec3f6176d0cd48698228410489'

# use the following metadata instead when developing/debugging with local node
#metadata:
#  source: ws://localhost:9944
#  blockHash: '0xd1ad168ff487544625b1f8c662725a6e5b9890f6a36cd30c42b3f170391f8ed0'

events:
  # members
  - members.MemberRegistered
  - members.MemberUpdatedAboutText
  - members.MemberUpdatedAvatar
  - members.MemberUpdatedHandle
  - members.MemberSetRootAccount
  - members.MemberSetControllerAccount

  # content directory
  - content.CuratorGroupCreated
  - content.CuratorGroupDeleted
  - content.CuratorGroupStatusSet
  - content.CuratorAdded
  - content.CuratorRemoved
  - content.ChannelCreated
  - content.ChannelUpdated
  - content.ChannelDeleted
  - content.ChannelCensored
  - content.ChannelUncensored
  - content.ChannelOwnershipTransferRequested
  - content.ChannelOwnershipTransferRequestWithdrawn
  - content.ChannelOwnershipTransferred
  - content.ChannelCategoryCreated
  - content.ChannelCategoryUpdated
  - content.ChannelCategoryDeleted
  - content.VideoCategoryCreated
  - content.VideoCategoryUpdated
  - content.VideoCategoryDeleted
  - content.VideoCreated
  - content.VideoUpdated
  - content.VideoDeleted
  - content.VideoCensored
  - content.VideoUncensored
  - content.FeaturedVideosSet
  - content.PlaylistCreated
  - content.PlaylistUpdated
  - content.PlaylistDeleted
  - content.SeriesCreated
  - content.SeriesUpdated
  - content.SeriesDeleted
  - content.PersonCreated
  - content.PersonUpdated
  - content.PersonDeleted

calls:
  # members
  - members.buyMembership
  - members.addScreenedMember
  - members.changeMemberAboutText
  - members.changeMemberAvatar
  - members.changeMemberHandle
  - members.setRootAccount
  - members.setControllerAccount

  # content directory
  - content.createCuratorGroup
  - content.deleteCuratorGroup
  - content.setCuratorGroupStatus
  - content.addCuratorToGroup
  - content.removeCuratorFromGroup
  - content.createChannel
  - content.updateChannel
  - content.deleteChannel
  - content.requestChannelTransfer
  - content.cancelChannelTransferRequest
  - content.acceptChannelTransfer
  - content.createVideo
  - content.updateVideo
  - content.deleteVideo
  - content.createPlaylist
  - content.updatePlaylist
  - content.deletePlaylist
  - content.setFeaturedVideos
  - content.createVideoCategory
  - content.updateVideoCategory
  - content.deleteVideoCategory
  - content.createChannelCategory
  - content.updateChannelCategory
  - content.deleteChannelCategory
  - content.createPerson
  - content.updatePerson
  - content.deletePerson
  - content.addPersonToVideo
  - content.removePersonFromVideo
  - content.censorVideo
  - content.censorChannel
  - content.uncensorVideo
  - content.uncensorChannel
  - content.createSeries
  - content.updateSeries
  - content.deleteSeries

outDir: ./generated/types
customTypes:
  lib: '@joystream/types/augment/all/types'
  typedefsLoc: '../types/augment/all/defs.json'
